### PR TITLE
[firstrun] (manjaro) reboot xfce for now

### PR DESCRIPTION
**Pull request by philmmanjaro**
currently Manjaro shells stuck after firstrun. As a workaround we reboot

### CODE REVIEW

**Comment by philmmanjaro** [comment]
we have to test more if it is needed or not ...

**Comment by MagicalTux** [comment]
Let's find what causes the issue and instead add the services to the "Before" part of the unit

**Comment by DimStar77** [comment]
Just a thought: do you have `systemd-firstboot` enabled? for openSUSE, I masked that service during image creation to be sure it does not interfere

**Comment by MagicalTux** [comment]
If we find this is an issue, we could add `systemd.firstboot=off` to our default kernel options

**Comment by philmmanjaro** [comment]
currently I'm about to test this out.

**Comment by philmmanjaro** [comment]
Na it still get stuck on first boot ...

image

**Comment by philmmanjaro** [comment]
On the second boot I see some interesting line ...

image

**Comment by zgrimshell** [comment]
Closing this one as it got solved in different PR.

**Pull request closed without merging**
